### ISSUE TITLE
Thread-Safety

### ISSUE THREAD

**Issue by Qli23** [b3b00/csly#155]
Hello b3b00,

If we need to parse a lot of strings in a multithreaded environment (all strings having the same syntax), do you recommend to use the same Parser instance everywhere?
In other words, are Lexer and Parser thread-safe?

Thanks

**Comment by b3b00** [comment]
## Parser

Syntax parser is  stateless (only shared data is its configuration which does not change after been built). So Syntax parser is thread safe.

But the Parser is not as the instance containing the visitor methods may have a state. You can avoir this using [context during visiting](https://github.com/b3b00/csly/wiki/BNF-Parser#using-a-context-during-syntax-tree-visiting).

## Lexer

### Regex Lexer
I'am sorry to say that I am not sure id regex lexer is thread-safe or not ! It uses IEnumerables (and yield keyword) and I don't know how the compiler and runtime manage this. Nevertheless I would guess that it should be thread-safe.
But I am not sure that is lexer is of great use anyway as it is too slow.

### Generic Lexer
Generic Lexer is stateless : only state is the FSM and it does not  have itself a state.

### conclusion
So I guess parser+lexer are  thread safe as long as you make sure that the instance used for building parser is itself thread safe and you can use a  [context during visiting](https://github.com/b3b00/csly/wiki/BNF-Parser#using-a-context-during-syntax-tree-visiting) to achieve this goal.

I must confess that I've never used CSLY in a multi-threaded context so that must confirm with a real world try.

**Comment by Qli23** [comment]
That's very clear. Thank you @b3b00

**Comment by b3b00** [comment]
Sorry I missed one thing reading my code : 
FSMLexer is not thread-safe as it have a state : its current position. So the generic lexer is not thread safe too.

I think this could be quiet easily addressed. Would like it ? I think it's an interresting issue that could block some use case. I will look at it anyway

**Comment by Qli23** [comment]
I wouldn't say no. If you manage to do this it would be very nice

**Comment by b3b00** [comment]
I let this issue opened as long I study a way to make generic lexer thread-safe

**Comment by b3b00** [comment]
Another good reason to address it is that it should solve issue #143 in a cleaner way

**Comment by b3b00** [comment]
I 've made a fix on branch [#155-thread-sage-generic-lexer](https://github.com/b3b00/csly/tree/bugfix/%23155-thread-sage-generic-lexer)
You can check if you want.
I still have to make a "crash test" throwing many thread using the same parser instance

**Comment by Qli23** [comment]
We made some tests with a Parallel.ForEach.
When using the master branch, we get exceptions, whereas with the branch [#155-thread-sage-generic-lexer](https://github.com/b3b00/csly/tree/bugfix/%23155-thread-sage-generic-lexer) all the threads end successfully.

**Comment by b3b00** [comment]
Thanks for your answer. I made the same and get the same results : error on dev branch and success on #155 branch.

**Comment by b3b00** [comment]
I've merged branch #155 to dev. and will release a nex version
