### ISSUE TITLE
Is there any way to get the line and column position (and length) in the parser method?

### ISSUE THREAD

**Issue by moe001** [b3b00/csly#244]
Is there any way to get the line and column position (and length) in the parser method?

e.g.
```c sharp
        [Operation((int) ExpressionToken.PLUS, Affix.InFix, Associativity.Right, 10)]
        [Operation("MINUS", Affix.InFix, Associativity.Left, 10)]
        public double BinaryTermExpression(double left, Token<ExpressionToken> operation, double right)
        {
            //////////////////
            // HERE
            //////////////////
            double result = 0;
            switch (operation.TokenID)
            {
                case ExpressionToken.PLUS:
                {
                    result = left + right;
                    break;
                }
                case ExpressionToken.MINUS:
                {
                    result = left - right;
                    break;
                }
            }

            return result;
        }
```

**Comment by b3b00** [comment]
Hello, ypu can get line and column on token with 
```
operation.Position.Line
// And
operation.Position.Column
```
Line length is not available.
I don't see the purpose of having the line length, could you explain ?

**Comment by moe001** [comment]
I mean the length of the expression part captured by the current method.
Like
> 5***33+22**

LengthOf(`33+22`)=5

**Comment by b3b00** [comment]
There is no way to get it directly with CSLY.
I still don't understand the use case that makes you need this length, furthermore an expression may be splitted on many lines and a length value may not have a real many in this case.

I will try to make an "as simple as possible" example on a branch. For this I must modify the result type of the ExpresionParser parser sample  in order to make it return a value (double type) along with positional information. Something like : 

```c# 
public class Result
    {
public double Value { get; set; }

        public int StartColumn { get; set; }

        public int EndColumn { get; set; }

        public int Column => EndColumn - StartColumn;
    }
```` 

In the end operator overloading may help getting the value more easily.

**Comment by b3b00** [comment]
Here is a sample that explain to calculate the "length" of a rule.

[https://github.com/b3b00/csly/tree/issue/244-example](https://github.com/b3b00/csly/tree/issue/244-example)

**Comment by moe001** [comment]
Wooow.
**Thank you**, help me greatly!
