### ISSUE TITLE
String escaping with backslash seems to escape too much of the string

### ISSUE THREAD

**Issue by cadmaticpgustafsson** [b3b00/csly#348]
Hello.

It seems that using the generic lexer, it consumes to much of the escape sequence when the default backslash ("\\") is used as the escape sequence.

For example, parsing the following string: "te\\\\st" should produce: "te\\\\st" however the actual output is: "te\st". Notice the one missing backslash. Also chaining backslashes causes the same problem: "te\\\\\\\\st" -> "te\st". 

Changing the default escape character to something else, seems to fix the problem.

I've attached a test project (.NET 6 and Visual Studio 2022), with a unit test containing my example.

It could be that I'm doing something wrong as well, in that case, please tell me 🙂. 
[EscapeTest.zip](https://github.com/b3b00/csly/files/10956829/EscapeTest.zip)

**Comment by b3b00** [comment]
Hello @cadmaticpgustafsson,

Thanks for your detailed issue. i particurlarly appreciate the test case project.

I will look at your issue quickly

**Comment by b3b00** [comment]
@cadmaticpgustafsson ,

I have mixed feelings about what you're asking.
My opinion about escape chars is that they are despecializing the char followig them to avoid special interpretation. 
So "\"" is in fact a despecialization of the double quote char " to avoid that the lexer think it 's a string ending delimiter. So in fact \" is really a single " char for the lexer client.

and so I think that the correct string value returned by the lexer should be
`"te\\st"`
the \ before both " are droped leaving " chars.
And equally the `\\` sequence transaltes to a single \ . To `\\\\` translates to `\\` 

there is an issue with the `\\\\` in your test case that translates to a single \ instead of 2. i will look at it and fix it.

**Comment by cadmaticpgustafsson** [comment]
@b3b00 
Thanks for the quick answer! After reading your response I agree with you. That "\\\\" should translate into just a single "\\", and similarly for more backslashes "\\\\\\\\" -> "\\\\".  

So I guess the real bug here is that escaping multiple backslashes always translates into just one.

**Comment by b3b00** [comment]
@cadmaticpgustafsson 

thanks, you get the point. I am looking at the multiple escaping issue. 

Olivier

**Comment by b3b00** [comment]
@cadmaticpgustafsson 

I've just understood what's happening. there are 2 escaping that happen :

1. first C# \ is escaping `\\\\` to `\\` 
2. then the generic lexer is esacping `\\` to `\`

Those multiple escaping layers are annoying and I often messing with them when dealing with regular expressions for example.

i still have to check some edge cases as `\"te\\\\\\\\st\"`should translates to  `"te\\st"` but appears as `"te\st"`

**Comment by b3b00** [comment]
I ve published a new nuget version that solve the issue we' ve found.

**Comment by cadmaticpgustafsson** [comment]
@b3b00 
Thanks for the quick fix! I tested with the new version and now it works correctly. 👍
